name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir uv
          uv venv
          source .venv/bin/activate
          uv sync

      - name: Run tests
        run: echo "Efetuar testes com o pytest"

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          # Nome da imagem
          tags: |
            jlsilva01/projeto-fastapi-satc:v${{ github.run_number }}
            jlsilva01/projeto-fastapi-satc:latest
          context: ./app
          file: ./Dockerfile
          push: true